### ISSUE TITLE
can the page open with a particular state and district pre-selected ?

### ISSUE THREAD

**Issue by aahnik** [misalraj/vaccine_availability_info#2]
```
domain.com/state/district
```

is something like this possible with streamlit?

passing some parameters to the app URL, so that the app loads with those defaults

**Comment by misalraj** [comment]
May be possible with ArgumentParser. Try that.

import argparse
parser = argparse.ArgumentParser(description='"some msg')

parser.add_argument("--state", help="state name")
parser.add_argument("--district", help="distcict name")
args = parser.parse_args()

print(args.state)        # this variable can assign 
print(args.disctrict)   

Run: 
streamlit run <app.py> -- --state "Jharkhand" --district "Ranchi"

Note: A double dash (`--`) is used to separate streamlit arguments from app arguments.

**Comment by misalraj** [comment]
.

**Comment by aahnik** [comment]
I am not talking about the cli.

From cli I just want to want to start the app normally. 

But in the url. Different people can select diff state and dist. And after that the url in the url bar should change, containing the state and district.

Now that url could be easily shared.


I think streamlit does not support such stuff. I have see docs.
